name: Publish to GitHub Packages

on:
  push:
    branches:
      - main 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.PACKAGES_PAT }}
        run: |
          ./gradlew publish
